name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for 
  # the main branch
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run 
# sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13','3.14']


    # Steps represent a sequence of tasks that will be executed as 
    # part of the job
    steps:
      # Checks-out your repository so your job can access it
      - name: Check-out repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests,dev]

      # Download nltk wordnet - ChatGPT was used to find the correct command to ensure the action runs
      - name: Download nltk wordnet 
        run: |
          python -m nltk.downloader wordnet omw-1.4 

      # Run pytest with coverage
      - name: Run tests with coverage
        run: |
          pytest --cov --cov-branch --cov-report=xml

      # Run style checker - ruff
      - name: Run style ruff checker
        run: |
          ruff check .
      
      # Upload coverage reports to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
